# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 944d4764461304d16269cccaba573c99f063e7148b7ce965acf6f072cc9442fa3307e7aa1fa8fbe5f05ac9a7d8a8d9d00c611a0b3807ffed6282b5b973fe4220

test:
  secret_key_base: 9eda08b5c99b980d51e57653bcb120d2a73d7e77f7fd10fd8be3d069e7777153ab3905970c3451467997ecd06d2fc3ab12ede6587ab288fab1f20169010801d4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
